networks:
    covid-17:
        ipam:
            driver: default
            config:
            - subnet: 172.31.0.0/24
services:
    db:
        build: ./mysql
        networks:
            covid-17:
                ipv4_address: '172.31.0.10'
        ports:
            - 3306:3306
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        # user: mysql
        user: "1000:50"
        container_name: covid_db
        environment:
            MYSQL_DATABASE: sampledb
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
    web:
       # restart: always
       build: ./python
       networks:
           covid-17:
              ipv4_address: '172.31.0.30'
       ports:
            - 8080:8080
       container_name: covid_py
       volumes:
           - "./python/workdir:/workdir"
       environment:
            TZ: "Asia/Tokyo"
       tty: true

